### ISSUE TITLE
Feature Request: Add Contribution Guidelines

### ISSUE THREAD

**Issue by kabugatti** [JunDevHarsh/ReadmeEase#2]
I would like to contribute by helping to define the contribution guidelines for the project, e.g naming guidelines, git commit message styles etc.

All this will be in a `CONTRIBUTION.md` file

**Comment by itsxharsh** [comment]
Thank you @grand-rick001, you can work on this issue. But remember, let the contributors know about contributing to the `dev` branch only not to the `main` branch.

**Comment by kabugatti** [comment]
Awesome, noted @JunDevHarsh

**Comment by itsxharsh** [comment]
Hello there @grand-rick001, just want to know about the updates regarding this issue.

**Comment by kabugatti** [comment]
Hey @JunDevHarsh , just finishing up, I'll make a PR within the course of the day.
