### ISSUE TITLE
[BUG] Footer not staying at the bottom of the 'files' page

### ISSUE THREAD

**Issue by Aadarsh805** [JunDevHarsh/ReadmeEase#4]
![image](https://user-images.githubusercontent.com/95094057/219557291-ff72a2ec-67c6-46db-83a6-31347e801deb.png)

**Comment by JunDevHarsh** [comment]
Dear @Aadarsh805,

I just wanted to express my gratitude for your work on identifying and reporting the bug in our project. Your attention to detail and willingness to help improve the project is greatly appreciated.

Thank you again for your valuable contribution to our project!

**Comment by Aadarsh805** [comment]
> Dear @Aadarsh805,
> 
> I just wanted to express my gratitude for your work on identifying and reporting the bug in our project. Your attention to detail and willingness to help improve the project is greatly appreciated.
> 
> Thank you again for your valuable contribution to our project!

If nobody picks it up by the end of this week, and you need help
I can fix this

**Comment by JunDevHarsh** [comment]
@Aadarsh805, sorry for not giving any updates regarding this issue. 

> I can fix this

Okay, I am assigning this issue to you. 

One approach I think would be great is just to replace the following code in `./src/pages/files/index.tsx`.

From:

```javascript
<div className="flex flex-row items-center justify-between w-full">
```

To:

```javascript
<div
  className={`mx-auto py-10 px-6 max-w-[1440px] w-full h-full ${
          process.env.NODE_ENV === "development"
            ? "min-h-[calc(100vh-162px)]"
            : "min-h-[calc(100vh-122px)]"
     }`}
>
```

**Comment by JunDevHarsh** [comment]
Remember to make a PR only to the `dev` branch, not the `main` branch.

**Comment by Aadarsh805** [comment]
it's better if some beginner can pick it up
but if no one picks it up in the next 5-6 days, then I'll do it
unassigning myself for now

**Comment by JunDevHarsh** [comment]
No worries,

**Comment by JunDevHarsh** [comment]
I am closing this issue as completed.
