### ISSUE TITLE
[DOCS] - Write 'npm run dev' instead of 'npm run start'

### ISSUE THREAD

**Issue by JunDevHarsh** [JunDevHarsh/ReadmeEase#7]
## Issue Description
The current documentation suggests using `npm run start` to start the development server. However, this command does not work as expected, and it results in an error. Instead, we should use `npm run dev` to start the development server.

## Steps to Reproduce
1. Go to the documentation
2. Look for instructions to start the development server
3. Follow the instructions, and you will see that the `npm run start` command does not work.

## Expected Behavior
The documentation should suggest using `npm run dev` instead of `npm run start`.

## Actual Behavior
The documentation suggests using `npm run start`, which does not work.

## Possible Solution
Update the documentation to suggest using `npm run dev` instead of `npm run start`.

**Comment by mohammedmoheed** [comment]
can i work on this

**Comment by JunDevHarsh** [comment]
I have seen that you already made a PR.
