### ISSUE TITLE
Feature Request: Add Github Link to Header Section

### ISSUE THREAD

**Issue by Vijaykv5** [JunDevHarsh/ReadmeEase#7]
![Capture](https://user-images.githubusercontent.com/94985341/222900123-4878ecc1-8bc6-403c-85b8-7f8f2e930522.PNG)

Add a github icon and  link to your profile

**Comment by itsxharsh** [comment]
Thank you @Vijaykv5 for raising this issue. The header section of the project is missing a link to the GitHub repository. It would be helpful to add a link to the repository to make it easier for users to access the source code.

**Comment by Vijaykv5** [comment]
May you assign it to me . I can check it out

**Comment by itsxharsh** [comment]
Thank you @Vijaykv5 for showing interest in contributing to this project. Just want to know about the process and what are you implementing here. Like, add a `Github` icon or something else.

**Comment by Vijaykv5** [comment]
Yeah basically a github icon at the top(Header) that links to this repo

**Comment by itsxharsh** [comment]
Okay, I am assigning this issue to you. Remember to update your fork with project's `dev` branch and then make a PR reference to the `dev` branch only.

**Comment by iONBain** [comment]
is the issue still open ? I can work on it if not moved

**Comment by itsxharsh** [comment]
Hello @iONBain, sorry for the late reply. Yes, the issue is still open. You can work on it if you want to. Reply if you want me to assign you this issue.

**Comment by iONBain** [comment]
Yes, I can work on it Harsh

**Comment by itsxharsh** [comment]
Thank you @iONBain for replying quickly, now you can work on it.

**Comment by iONBain** [comment]
Hi @JunDevHarsh, I have opened a PR (feature: added github link in header #13) for this feat. Pls review and take necessary actions. Thanks.

**Comment by iONBain** [comment]
I have opened a PR #14 for merging to dev branch as mentioned.

**Comment by itsxharsh** [comment]
Thank you @iONBain for contributing to this project. Now, I am closing this issue as completed.
